### ISSUE TITLE
Application Error when a user submits an empty Event/New

### ISSUE THREAD

**Issue by CyberStrike** [CyberStrike/soflo#22]
```bash
[web.1]: Processing by EventsController#create as HTML
[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"Fj2zTdn9g8pSbQHbiF0Z5NyZC5f32tx+53EYGKxYwn0=", "event"=>{"title"=>"", "start(1i)"=>"2015", "start(2i)"=>"3", "start(3i)"=>"30", "start(4i)"=>"14", "start(5i)"=>"57", "location"=>{"name"=>"", "unit"=>"", "streetnumber"=>"", "street"=>"", "city"=>"", "state"=>"", "zip"=>"", "country"=>"", "long_address"=>""}, "ticketurl"=>"", "description"=>""}, "commit"=>"Save"}
2015-03-30T18:57:44.860132+00:00 heroku[router]: at=info method=POST path="/events" host=www.soflo.rocks request_id=7e22aefe-15c7-4d73-89c2-5b51cda3aaea fwd="50.206.104.14" dyno=web.1 connect=1ms service=32ms status=500 bytes=1669
[web.1]: Completed 500 Internal Server Error in 24ms
[web.1]:   Rendered events/new.html.slim within layouts/application (6.8ms)
[web.1]:   Rendered events/_form.html.slim (6.5ms)
[web.1]:
[web.1]: ActionView::Template::Error (undefined method `model_name' for NilClass:Class):
[web.1]:     31:     .icon-content
[web.1]:     33:         = text_field_tag :event_location, @location, class:'form-control', placeholder: 'Add Location', tabindex: autoTabIndex, name:''
[web.1]:     32:       .form-group
[web.1]:     34:         = f.fields_for @location do |lf|
[web.1]:     35:           = lf.hidden_field :name
[web.1]:     36:           = lf.hidden_field :unit
[web.1]:     37:           = lf.hidden_field :streetnumber
[web.1]:   app/views/events/_form.html.slim:34:in `block in _app_views_events__form_html_slim__4540819927304679208_70241625713840'
[web.1]:   app/views/events/_form.html.slim:1:in `_app_views_events__form_html_slim__4540819927304679208_70241625713840'
[web.1]:
[web.1]:   app/views/events/new.html.slim:6:in `_app_views_events_new_html_slim___2633371114358337405_70241625790480'
[web.1]:   app/controllers/events_controller.rb:60:in `block (2 levels) in create'
[web.1]:   app/controllers/events_controller.rb:55:in `create'
```

**Comment by CyberStrike** [comment]
Instead of rendering with error messages as it does in develompent it just breaks in production.
